language: node_js
node_js:
  - "8"
services: mongodb
cache:
  npm: true
install:
  - npm install
script:
  - npm install codecov -g
  - npm run build
  - npm t -- --coverage
after_success:
  - codecov